import type { BpmnDocument } from '../../contracts/bpmn.ts';

export function createBpmnDocument(
  dossierId: string,
  modelId: string,
  name = 'Processus de diagnostic',
): BpmnDocument {
  return {
    id: 'bpmn-diagnostic',
    dossier_id: dossierId,
    model_id: modelId,
    name,
    revision: 0,
    status: 'draft',
    participants: [
      {
        id: 'participant-consultant',
        label: 'Cabinet conseil',
        process_id: 'process-consultant',
      },
      {
        id: 'participant-client',
        label: 'Entreprise cliente',
        process_id: 'process-client',
      },
    ],
    lanes: [
      {
        id: 'lane-consultant',
        label: 'Consultant',
        participant_id: 'participant-consultant',
      },
      { id: 'lane-expert', label: 'Expert', participant_id: 'participant-consultant' },
      { id: 'lane-direction', label: 'Direction', participant_id: 'participant-client' },
    ],
    nodes: [
      {
        id: 'start-consultant',
        type: 'startEvent',
        label: 'Demande reçue',
        process_id: 'process-consultant',
        participant_id: 'participant-consultant',
        lane_id: 'lane-consultant',
        parent_subprocess_id: null,
        position: { x: 40, y: 80 },
      },
      {
        id: 'task-cadrage',
        type: 'userTask',
        label: 'Cadrer la mission',
        process_id: 'process-consultant',
        participant_id: 'participant-consultant',
        lane_id: 'lane-consultant',
        parent_subprocess_id: null,
        position: { x: 220, y: 80 },
      },
      {
        id: 'task-analyse',
        type: 'serviceTask',
        label: 'Analyser les données',
        process_id: 'process-consultant',
        participant_id: 'participant-consultant',
        lane_id: 'lane-expert',
        parent_subprocess_id: null,
        position: { x: 400, y: 180 },
        execution: 'disabled',
      },
      {
        id: 'subprocess-restitution',
        type: 'subprocess',
        label: 'Préparer la restitution',
        process_id: 'process-consultant',
        participant_id: 'participant-consultant',
        lane_id: 'lane-consultant',
        parent_subprocess_id: null,
        position: { x: 580, y: 80 },
        collapsed: true,
      },
      ...[
        ['synthese', 'Rédiger la synthèse'],
        ['revue', 'Relire les constats'],
        ['support', 'Préparer le support'],
      ].map(([id, label], index) => ({
        id: `task-${id}`,
        type: 'manualTask' as const,
        label,
        process_id: 'process-consultant',
        participant_id: 'participant-consultant',
        lane_id: 'lane-consultant',
        parent_subprocess_id: 'subprocess-restitution',
        position: { x: 120 + index * 180, y: 320 },
      })),
      {
        id: 'end-consultant',
        type: 'endEvent',
        label: 'Restitution prête',
        process_id: 'process-consultant',
        participant_id: 'participant-consultant',
        lane_id: 'lane-consultant',
        parent_subprocess_id: null,
        position: { x: 780, y: 80 },
      },
      {
        id: 'task-validation-client',
        type: 'userTask',
        label: 'Valider les constats',
        process_id: 'process-client',
        participant_id: 'participant-client',
        lane_id: 'lane-direction',
        parent_subprocess_id: null,
        position: { x: 580, y: 500 },
      },
    ],
    flows: [
      {
        id: 'flow-cadrage-analyse',
        type: 'sequenceFlow',
        source_id: 'task-cadrage',
        target_id: 'task-analyse',
      },
      {
        id: 'message-validation',
        type: 'messageFlow',
        source_id: 'subprocess-restitution',
        target_id: 'task-validation-client',
      },
    ],
    view: {
      open_process_id: 'process-consultant',
      breadcrumb_ids: ['bpmn-diagnostic', 'process-consultant'],
      selected_id: 'subprocess-restitution',
      zoom: 1,
    },
  };
}
